import type { Metadata } from 'next';

import CssBaseline from '@mui/material/CssBaseline';
import Hero from '@/components/sections/Hero';

import ThemeWrapper from '@/themes/';

import { getPageData } from '@/data/page';

export const metadata: Metadata = {
  title: 'DJ LP',
  description: 'Generated by create next app',
};

const HomePage = async () => {
  const data = await getPageData();
  const { theme, primary_color } = data;

  return (
    <ThemeWrapper theme={theme} primaryColor={primary_color}>
      <CssBaseline />
      <Hero />
    </ThemeWrapper>
  );
}


export default HomePage;