import type { Metadata } from 'next';

import CssBaseline from '@mui/material/CssBaseline';
import Pricing from '@/components/Pricing';
import Hero from '@/components/Hero';

import { ThemeProvider } from '@mui/material/styles';

import { defaultTheme, materialTheme, inkiTheme } from '@/themes';

import { getPageData } from '@/lib/data';

export const metadata: Metadata = {
  title: 'DJ LP',
  description: 'Generated by create next app',
};

const HomePage = async () => {
  const data = await getPageData();
  const { theme } = data;

  const themeTree = {
    default: defaultTheme,
    material: materialTheme,
    inki: inkiTheme,
  }

  return (
    <ThemeProvider theme={themeTree[theme as keyof typeof themeTree]}>
      <CssBaseline />
      <Hero text="hero" />
      <Pricing />
    </ThemeProvider>
  );
}


export default HomePage;